image: archlinux:latest

before_script:
  - echo "Install zip dependency and update system"
  - pacman -Syu zip --noconfirm --needed

epub:
  stage: build
  script:
    - bash ./scripts/pack-all.sh CI
  artifacts:
    paths:
      #- Omniscient Reader's Viewpoint - Sing-shong (singsyong)-clean.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong).epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-Illustrated.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt1.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt2.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt3.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt4.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt5.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt6.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt7.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol1_Pt8.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol2_Pt1.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol2_Pt2.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol2_Pt3.epub
      - Omniscient Reader's Viewpoint - Sing-shong (singsyong)-NaverVol2_Pt4.epub
    expire_in: 1 day
